CPPFLAGS := -fpermissive

BINS = _person person_ _Main.class Main_.class _Person.class Person_.class

all: $(BINS)
trash += $(BINS)

_person: _person.cpp

person_: person_.cpp

include ../../Makefile
